name: medication_compliance_tool
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  async: ^2.12.0
  fake_async: ^1.3.2
  leak_tracker: 10.0.8  # Downgraded to 10.0.8 to avoid conflict with flutter_test
  material_color_utilities: 0.11.1  # Downgraded to 0.11.1 to avoid conflict with flutter_test
  vm_service: ^14.3.1  # Keep vm_service version 14.3.1
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  sqflite_common_ffi: ^2.3.0  # Add this for desktop database support
  path: ^1.8.3
  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.2
  google_fonts: 6.2.1
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.0.2
  flutter_local_notifications: ^9.1.4
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/medication_compliance_tool.db

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400

  # Removed the Linux specific configuration from flutter_local_notifications
  # Since we're targeting only Android and iOS
