name: medication_compliance_tool
description: "A new Flutter project."
version: 0.1.0
publish_to: none  # This prevents the package from being published

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0 
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  logging: ^1.0.2
  path: ^1.8.3
  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.2
  google_fonts: 6.2.1
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.0.2
  provider: ^6.0.3
  async: ^2.12.0
  fake_async: ^1.3.2
  leak_tracker: 10.0.8
  material_color_utilities: 0.11.1
  vm_service: ^14.3.1 
  flutter_appauth: ^9.0.0 

  # Database handling
  sqflite_common_ffi: ^2.3.4  # For desktop (Windows, Mac, Linux)
  sqflite_common_ffi_web: ^1.0.0  # Correct package for web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
